# Generated by Django 2.1.5 on 2019-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputa', models.IntegerField(default='')),
                ('inputb', models.IntegerField(default='')),
            ],
        ),
    ]
