# Generated by Django 2.1.5 on 2019-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('mobile', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
